<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Tarihce.aspx.cs" Inherits="Tarihce" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div class="asil">
        <img src="image/genel.jpg" style="float:left;padding:20px 20px 7px 10px;" />
        <h2>TARİHÇE</h2>
        <p>HEDİ, anlamı çeşitli dönemlerde yapılmış olan Osmanlı dönemi haritalarda ve Kayıtlarında gerek telefuz farklılığından gerekse farklı zamanlarda farklı memurların yazımlarından hedi veya hidi olarak kaydedilmiştir.
        Ancak Osmanlı basılı evraklarının hemen hepsinde hedi olarak geçtiği görülmektedir.</p>
        <p>Türkçe etimolojik sözlüklerde H,edi olarak bakıldığında mana olarak SAHİP (halk dili) veya Hed-i HACDA KESİLEN KURBAN, karşılığı çıkmakla beraber Osmanlıca sözlük ve lügatlarda Hedi karşılığı-MÜRŞİT ve BOYUN anlamlarına geldiği görülmektedir.</p>
        <p>1518 tarihli Osmanlı kayıtlarında HİDİ CEMAAT-I ETRAK olarak kayda giren köyün hane ve nüfus sayısı 1 olması da dönem olarak köyün isim manasını Mürşit olarak edebilmemize sebep teşkil edebilir.
Ancak dönem itibariyle göçle gelen Türkmenlerin yerleştikleri yerlere ya geldikleri yörelerin isimlerini verdikleri veya arazi yapısını benzettikleri şekillerin veya nesnelerin isimleriyle adlandırdıkları yaygın olarak görülmektedir. Coğrafik olarak bölgeye bakıldığında Fırat nehri yatağındaki köylerle dönemin cazibe merkezi olan Harput Sancağına ulaşım yolu üzerinde bulunan köyün BOYUN anlamında da Hedi olarak adlandırılmış olma ihtimali de vardır.
</p>
        <p>Miladi 1518 Osmanlı kayıtlarına göre köyün 1 hane ve 1 nüfus olduğu görülmektedir. Aynı kayıtlarda bazı köy ve mezralar için çok az nüfus ve hane gösterilirken genelde eski köy ise viran veya boş tabirlerini kullanılmış olmakla birlikte Hedi köyü için bu tabir kullanılmamış ve bir sonraki kayda kadar köyden vergi de tahsil edilmemiştir. Bu bize köyün tahminen 1500 lü yılların başlarında yine 1518 kayıtlarında bir şahıs tarafından kurulduğu gerçeğini göstermektedir.</p>
        <p>Çemişgezek sancağı Keban nahiyesine bağlı olan köy, Keban nahiyesindeki madenlerin keşfi ve işletilmesi sonucu Keban’ın önem kazanıp idari şekil olarak sancak olmasıyla birlikte Çemişgezek’le olan idari ilişki son bulmuştur. Halen ormanlık olan köyün o yıllarda, bugünkü Nüşkuşak, İbolar, Ağrulu ve Hedi köyünün bulunduğu alanın tamamının daha büyük meşe ormanlığına sahip olması, maden işletmeciliğinde kullanılan odun kömürünün büyük bir kısmının buralardan sağlanması yoluna gidilmesine sebep olmuştur. Ağruluda ve Hedi’ deki grodu dağının dibinde bulunan kömürlüklerde hazırlanan odun kömürü cumhuriyet yıllarına kadar Gümüş ve kurşunun eritilmesi için kullanılmış bu meşe ormanları daha sonra köy tüzel kişiliğine devredilmiştir. Bu dönemlerde köyde yerleşik düzene geçilmesi hızlanmıştır. Halen meşelik içerisinde kömürlük diye adlandırılan yerde kömür ocağının kalıntıları durmaktadır.Bu hususta yine rivayet edilen tarihi olaylardan biride o dönemlerde köyde yaşayan Akoğlu diye biri meşelerin kesilmesine mani olması ve Keban dan gönderilen askeri kuvvet tarafından öldürülmesidir.Bu rivayette adı geçen şahsın birde yazılı lengerinin (tepsi) olduğu ve bu tepsininde Köy sakinlerinden gıldir İboşun oğlu salih Tuncer’de( Amerikan Salih) bulunduğu söylenmektedir.</p>
        <p>Tarih de iki Türk oymağı Köy mezrası içerisindeki kale mevkisine yerleşerek etrafında bulunan araziyi “Palaklı” ve etraf bölgelerini de satın alarak buralara yerleşmişler.
Davarcılıkla uğraşan bu oymaklar zaman zaman Hırdışlar, Arapkirlinin yeri ve mağara başı denilen yerlere kadar gelerek hayvanlarını buralarda otlatırlarmış.Daha sonraları bu iki sülale köyde kortik mahalledeki şimdiki Ali Gülaydın ’ın evinin yerine ve Kara Mehmet Erenin evinin yerine ev yapıp yerleşik düzene geçmişler.Bu ailelerden birisi Hacı Said Ağanın biriside Şimdiki osogilin dedeleridir….Bu iki ailenin tarihinde çocuklarının bugüne kadar hep Ali ve Mehmet olarak gelmesi ve son olarak da Ali, Mehmet ve Abdullah olarak üç kardeş olarak isim aldıkları da kayıt edilmektedir. Bu üç kardeşin biri Abdullah Demirin evinin bulduğu yerde, biri yine Ali Gülaydın’ın evinin bulunduğu yerde, diğeride Osman çavuşun yani şimdiki osogilin evinin bulunduğu yere ev yaparak yerleşmişlerdir.
</p>
        <p>Köyün ilk yerleşim merkezlerinin Hırdışlar mevki, mağara başı, arılık önü ve yukarı mezarlığın üstündeki Arapkirlinin bahçeleri yerinde ayrı üç mezra halinde olduğu ve buralarda oturan halkın göçebe olup davarcılıkla uğraştığı da kayıtlar arasındadır.Bu sözü geçen yerleşim merkezlerinde halen ev temellerinin mevcuyeti buraların ilk yerleşim yerleri olduğunuda kamıtlar niteliktedir. Hırdışlarda oturanların cambenin pınarına gelerek su götürdükleride aşikardır.Topbaş, Abbas ağanın yurdu ve beyler yurdu yazlık yerleri olduğu tespit edilmiştir.</p>
        <p>Köye eski Türk ailelerinden Sado lakaplı aile ilk olarak yerleşmiştir. Keban’a gelen Selçuklu Türk Beylerinin yazlıklarının Birvan ’da ve bu köyde olduğu da bilinmektedir. Hedi Köyüne Mekke, İran, Azarbeycan, Arnavutluk, Van, Bitlis, Erzincan, Erzurum, İspir, Oltu, Keban, Pertek, Çemişgezek, Kağızman Karavenk Köyü, Arapkir, Üngüzek, Çöteli, Çakmak, Sağman, Koruk, Birvan, Alaca, Obuz, Hal gibi merkezlerden gelip yerleşenler olduğu gibi, Abo kahyagil ve Kizirler gibi ailelerin Balkan Göçmeni olarak sağmana oradan da Hedi’ye geldiği söylenmektedir. Köy 1920-30 yıllar da çok kalabalık ve nahiye niteliğindedir. Nahiye Müdürlüğünü de yine Hacı Said Ağanın yaptığı söylenmektedir. Hatta Keban dan Hacusura gelerek yerleşen Ayan Ağa ismindeki şahıs Hedi köyünün kalabalık olması nedeniyle öldükten sonra kendisinin buraya defnedilmesini vasiyet etmiştir. Kebana giden yol üzerindeki aşağı mezarlıkta mezarı bulunan Ayan Ağa, burdan geçen yolcuların kendisi için fatiha okuması için bu vasiyeti ettiği söylenmektedir.</p>
        <p>Hedi Köyü, Keban’a 16yy da, Çemişgezek sancağı Keban nahiyesi ve sonraki yüzyıllarda çeşitli idari yapılanmalarda Keban’ın gerek eyalet gerek sancak gerekse Vilayet olarak çeşitli statüsünün değişmesine rağmen 2 Haziran 1953 yılında idari olarak Elazığ merkez ilçeye bağlanmış ve halen bu konumdadır.
Bugünki haliyle Elazığ merkez ilçeye bağlı olan Hedi, şehre 42 km uzaklıkta ve etrafı dağlarla çevrili bir vadi de kurulmuş şirin bir köydür. Hedi köyüne Keban ilçesi güzergâhından Cip Köyü ve Poyraz köyünden geçilerek Çemişgezek güzergâhına dönülüp, Alpagut, çöteli, Dişidi, Köylerinden geçilip Hal köyü yol ayrımından sağa dönülerek 10 km sonra varılır. Güneyinde Hal ve Hacusur köyü, Kuzey batısında İbolar, doğusunda Balıbey ve Üngüzek köyü ve Batısında Birvan, Mişelli ve Hamzikan köyleri ile çevrili, mera alanı geniş köylerden biridir.
</p>
    </div>
</asp:Content>

